services:
  albina-online:
    container_name: albina-online
    build:
      context: ./AlbinaOnline
      dockerfile: Dockerfile.prod
    ports:
      - "11759:11759"
    env_file:
      - ./AlbinaOnline/.env
      - ./AlbinaOnline/.env.local
    restart: always

  albina-api:
    container_name: albina-api
    build:
      context: ./AlbinaApi
      dockerfile: Dockerfile.prod
    ports:
      - "11750:11750"
    volumes:
      - ./AlbinaMediaBd:/localstorage
      - /home/Itto/.AlbinaOnlineSecrets/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:ro
      - /home/Itto/.AlbinaOnlineSecrets/pfx/dataprotection.pfx:/app/secrets/datakey.pfx:ro
    env_file:
      - ./AlbinaApi/.env
      - ./enviroment-files/.env.database
    environment:
      - KEYS_LOCATION=/root/.aspnet/DataProtection-Keys
      - PFX_LOCATION=/app/secrets/datakey.pfx
    depends_on:
      - albina-db
    restart: always

  albina-db:
    image: postgres:16
    container_name: albina-db
    ports:
      - "6543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./enviroment-files/.env.database
    restart: always

volumes:
  postgres-data:
    external: true
    name: albina-db-v2
